# Generated by Django 5.1.1 on 2024-09-29 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=60)),
                ('course_duration', models.IntegerField()),
                ('course_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='login_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.CharField(max_length=400)),
                ('notification_date', models.DateField()),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='staff_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=30)),
                ('staff_email', models.CharField(max_length=30)),
                ('staff_phone', models.BigIntegerField()),
                ('staff_dob', models.DateField()),
                ('staff_code', models.CharField(max_length=10)),
                ('STAFF_LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='COLLEGE_APP.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='student_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=30)),
                ('student_email', models.CharField(max_length=30)),
                ('student_phone', models.BigIntegerField()),
                ('student_current_sem', models.CharField(max_length=30)),
                ('student_dob', models.DateField()),
                ('student_admission_number', models.CharField(max_length=10)),
                ('STUDENT_COURSE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='COLLEGE_APP.courses')),
                ('STUDENT_LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='COLLEGE_APP.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=500)),
                ('reply', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('replied_status', models.BooleanField(default=False)),
                ('STUDENT_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='COLLEGE_APP.student_profile')),
            ],
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=30)),
                ('COURSE_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='COLLEGE_APP.courses')),
            ],
        ),
        migrations.CreateModel(
            name='notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_note', models.FileField(upload_to='')),
                ('STAFF_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='COLLEGE_APP.staff_profile')),
                ('SUBJECT_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='COLLEGE_APP.subject')),
            ],
        ),
    ]
